services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: xray-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: xray-iot
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - xray-network

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: xray-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - xray-network

  # Producer Service
  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    container_name: xray-producer
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - xray-network

  # Consumer Service
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: xray-consumer
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/xray-iot?authSource=admin
      - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - xray-network

  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: xray-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/xray-iot?authSource=admin
    depends_on:
      - mongodb
    networks:
      - xray-network

volumes:
  mongodb_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  xray-network:
    driver: bridge
