services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: xray-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: xray-iot
    volumes:
      - mongodb_data_dev:/data/db
      - ./docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - xray-network-dev

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: xray-rabbitmq-dev
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data_dev:/var/lib/rabbitmq
    networks:
      - xray-network-dev

volumes:
  mongodb_data_dev:
    driver: local
  rabbitmq_data_dev:
    driver: local

networks:
  xray-network-dev:
    driver: bridge
